### ISSUE TITLE
Errors opening dialog in 1.6.1

### ISSUE THREAD

**Issue by butlermatt** [MikeMitterer/dart-material-design-lite#25]
Using this sample:
https://gist.github.com/butlermatt/10dbb29833c09ef0aec3

I receive the following stack trace when trying to open the dialog (with the button). Note in the sample, index.html and main.dart are in the web directory not root of the project.

```
Exception: Uncaught Error: Closure call with mismatched arguments: function 'dialog'

NoSuchMethodError: method not found: 'dialog'
Receiver: Instance of 'ExampleDialog'
Arguments: []
Stack Trace:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      _LocalInstanceMirror._invokeGetter (dart:mirrors-patch/mirrors_impl.dart:535)
#3      _LocalInstanceMirror._getFieldSlow (dart:mirrors-patch/mirrors_impl.dart:447)
#4      _LocalInstanceMirror.getField (dart:mirrors-patch/mirrors_impl.dart:466)
#5      Invoke.field.<anonymous closure> (package:mdl/src/application/mirrors/Invoke.dart:82:71)
#6      List.forEach (dart:core-patch/growable_array.dart:234)
#7      Invoke.field (package:mdl/src/application/mirrors/Invoke.dart:77:15)
#8      _TextFieldObserver.observe (package:mdl/src/directive/components/model/ModelObserver.dart:52:41)
#9      MaterialModel._setupObserver (package:mdl/src/directive/components/MaterialModel.dart:102:39)
#10     MaterialModel.refresh (package:mdl/src/directive/components/MaterialModel.dart:81:9)
#11     refreshComponentsInSubtree.<anonymous closure> (package:mdl/src/core/utils.dart:162:57)
#12     List.forEach (dart:core-patch/growable_array.dart:234)
#13     refreshComponentsInSubtree (package:mdl/src/core/utils.dart:160:36)
#14     refreshComponentsInSubtree.<anonymous closure> (package:mdl/src/core/utils.dart:158:65)
#15     Object&ListMixin.forEach (dart:collection/list.dart:63)
#16     refreshComponentsInSubtree (package:mdl/src/core/utils.dart:158:26)
#17     refreshComponentsInSubtree.<anonymous closure> (package:mdl/src/core/utils.dart:158:65)
#18     Object&ListMixin.forEach (dart:collection/list.dart:63)
#19     refreshComponentsInSubtree (package:mdl/src/core/utils.dart:158:26)
#20     refreshComponentsInSubtree.<anonymous closure> (package:mdl/src/core/utils.dart:158:65)
#21     Object&ListMixin.forEach (dart:collection/list.dart:63)
#22     refreshComponentsInSubtree (package:mdl/src/core/utils.dart:158:26)
#23     _MaterialDialogComponent.parentScope= (package:mdl/src/dialog/components/MaterialDialogComponent.dart:91:9)
#24     MaterialDialog.show.<anonymous closure> (package:mdl/src/dialog/MaterialDialog.dart:157:33)
#25     _RootZone.runUnary (dart:async/zone.dart:1166)
#26     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#27     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#28     _Future._completeWithValue (dart:async/future_impl.dart:368)
#29     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#31     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#32     _ScheduleImmediateHelper._handleMutation (dart:html:42567)
undefined:1 undefined
```

I've also tried a `pub cache repair` to verify it was not a corrupted package.

**Comment by MikeMitterer** [comment]
Please remove the `dialog.` from mdl-model

**Comment by butlermatt** [comment]
Perfect! That did the trick. Thanks. I would have never found that from the error haha
